setHerokuVars.py

Adds protection against badly formatted lines in `setHerokuVars.py`, as implemented in the rest of the projects

Add protection against badly formatted lines in setHerokuVars.py

---

.gitignore
README.md
pom.xml
src/main/java/edu/ucsb/changeme/entities/OnlineOfficeHours.java
src/main/java/edu/ucsb/changeme/entities/Tutor.java
src/main/java/edu/ucsb/changeme/entities/TutorAssignment.java
src/main/java/edu/ucsb/changeme/models/Course.java
src/main/resources/data.sql.SAMPLE
src/test/java/edu/ucsb/changeme/entities/OnlineOfficeHoursTests.java
src/test/java/edu/ucsb/changeme/entities/TutorAssignmentTests.java
src/test/java/edu/ucsb/changeme/entities/TutorTests.java

Resolves #7.
Note: the commit history will clean up once #4 is merged into main and we can rebase.

Sc tk al add harcoded fixtures and three tables

---

javascript/package-lock.json
javascript/package.json
javascript/src/main/App.js
javascript/src/main/components/Nav/AppNavbar.js
javascript/src/main/components/TutorAssignment/TutorAssignmentForm.js
javascript/src/main/components/TutorAssignment/TutorAssignmentTable.js
javascript/src/main/pages/TutorAssignment/NewTutorAssignment.js
javascript/src/main/pages/TutorAssignment/TutorAssignment.js
javascript/src/main/services/TutorAssignment/TutorAssignmentService.js
javascript/src/main/utils/quarter.ts
javascript/src/react-app-env.d.ts
javascript/src/test/components/Courses/CourseTable.test.js
javascript/src/test/components/TutorAssignment/TutorAssignmentForm.test.js
javascript/src/test/components/TutorAssignment/TutorAssignmentTable.test.js
javascript/src/test/pages/TutorAssignment/TutorAssignment.test.js
javascript/src/test/utils/quarter.test.ts
javascript/tsconfig.json
src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
src/main/java/edu/ucsb/ucsbcslas/controllers/TutorAssignmentController.java
src/main/java/edu/ucsb/ucsbcslas/repositories/CourseRepository.java
src/main/java/edu/ucsb/ucsbcslas/repositories/TutorAssignmentRepository.java
src/main/java/edu/ucsb/ucsbcslas/repositories/TutorRepository.java

Merging TutorAssignment backend with Tutor backend/frontend in order to conditionally display “edit/delete” for the instructor role

Merging TutorAssignment backend with Tutor

---

javascript/package-lock.json
javascript/src/main/App.js
javascript/src/main/components/Admin/LoginTable.js
javascript/src/main/components/Nav/AppNavbar.js
javascript/src/main/pages/Admin/ViewLogins.js
javascript/src/test/components/Admin/LoginTable.test.js
javascript/src/test/pages/Admin/ViewLogins.test.js
pom.xml
src/main/java/edu/ucsb/ucsbcslas/controllers/LoginsController.java
src/main/java/edu/ucsb/ucsbcslas/documents/Login.java
src/main/java/edu/ucsb/ucsbcslas/repositories/LoginsRepository.java
src/main/java/edu/ucsb/ucsbcslas/services/Auth0MembershipService.java
src/test/java/edu/ucsb/ucsbcslas/controllers/LoginsControllerTests.java
src/test/java/edu/ucsb/ucsbcslas/documents/LoginTests.java
src/test/java/edu/ucsb/ucsbcslas/services/Auth0MembershipServiceTests.java

mw - Frontend from issue #34 and backend from issue #33 of logins function implemented.
On the front end, admins can view a list of logins to the app, with timestamp, email, and first/last name of each user.
On the back end, a MongoDB database stores the table of logins.  The user information and corresponding timestamp is logged every time `isMember` or `isAdmin` is called in `Auth0MembershipService.java`

6pm b track logins

---

javascript/src/main/App.js
javascript/src/main/components/Nav/AppNavbar.js
javascript/src/main/components/TutorHistory/TutorHistoryForm.js
javascript/src/main/pages/TutorHistory/TutorHistory.js
javascript/src/main/services/TutorHistory/TutorHistoryService.js
javascript/src/test/App.test.js
javascript/src/test/components/TutorHistory/TutorHistoryForm.test.js
javascript/src/test/pages/TutorHistory/TutorHistory.test.js
javascript/src/test/services/TutorHistoryService.test.js

In this PR issue #30 is addressed where we add the front end to allow a user to search a course number (Ex. CMPSC 156, etc), then get the history of tutors who have been assigned to the course.

6pm b course tutor history frontend

---

javascript/src/main/pages/Courses/Courses.js

Steps to reproduce:
1. Visit the page https://proj-ucsb-cs-las.herokuapp.com/courses
2. Download a CSV
* Observed: The course number column is empty of data
* Desired: The course number column is filled with correct data

6pm d BUG FIX to csv download, repair missing course number column

---

src/main/java/edu/ucsb/ucsbcslas/advice/AuthControllerAdvice.java
src/main/java/edu/ucsb/ucsbcslas/controllers/RoleController.java

This ensures that users appear in the Admin panel where
they can be promoted to Admin, or demoted to non-admin
Closes #88

pc - add users into AppUser table when  is accessed

---

javascript/src/main/pages/Tutor/Tutor.js

Fixes bug in Tutor.js
Closes #141

Fixed bug in Tutor.js only showing tutor table to instructors 

---

javascript/src/stories/components/Courses/CourseTable.stories.js

Resolves #154.
Implements Storybook functionality for CourseTable from components/Courses/CourseTable, allowing for on-the-fly testing.

7pm-1 Storybook for CourseTable

---

.github/workflows/publish-docs-to-github-pages-qa.yml
.github/workflows/publish-docs-to-github-pages.yml
javascript/.storybook/main.js
javascript/.storybook/webpack-plugin-fail-build-on-warning.js
javascript/package-lock.json
javascript/package.json

In this PR, we set up a GitHub workflow to publish the storybook for the repo.
The storybook is published on GitHub pages in two separate repos:
* https://ucsb-cs156-s21/proj-ucsb-cs-las-docs for the production version of the documentation
- Link to page: https://ucsb-cs156-s21.github.io/proj-ucsb-cs-las-docs
- Note that this page will NOT be updated until this PR is merged.
* https://ucsb-cs156-s21/proj-ucsb-cs-las-docs-qa as a staging/qa site for draft versions contained in PRs
- Link to page: https://ucsb-cs156-s21.github.io/proj-ucsb-cs-las-docs-qa
- This page should be active immediately 
One of the workflows is set up to publish to the production site, i.e. <https://ucsb-cs156-s21.github.io/proj-ucsb-cs-las-docs>, only on a push to the main branch (i.e. when a PR is merged.)
The …

Staff s21 publish docs

---

javascript/src/main/pages/Admin/QuarterFilter.js

In this PR, we added some instruction to Quarter Filter page so the user know what the page is for.

cx 6pm-1 Add Instruction to Quarter Filter

---

javascript/src/index.js

finished the Toast Notifications Story from section on 5/11/2021.

cx - 6pm-3 finished Toast notifications with Martin

---

.github/workflows/contribution-requirements.yml
dangerfile.js

This PR adds a GitHub Actions workflow that checks for common mistakes in PRs and provides automated feedback about what issues were found and how the contributor can fix their PR.
To see the workflow in action, see #226

ci: add Danger checks for common PR issues

---

javascript/src/main/pages/TutorAssignment/TutorAssignments.js

added spacing between the "New Tutor Assignment" Button and the Tutors table on the Tutor Assignment page

wp - 6pm-2 Tutor Assignment Spacing

---

javascript/src/main/pages/OfficeHours/OfficeHours.js

Added a Download CSV button that downloads all the office hour data onto local machine

dw - 6pm-4-Add download csv button for Office Hours

---

javascript/src/main/pages/Admin/ViewLogins.js
javascript/src/main/pages/TutorAssignment/TutorAssignments.js

Stored the button on the Tutor Assignments page as a variable to avoid duplicating the markup for it.
Also replaced the hardcoded `style` attributes with the appropriate Bootstrap utility classes in the following locations:
1. Header on the Admin/View Logins page
2. Button on the Tutor Assignments page

rt - 6pm-2 Use Bootstrap classes for styling on Admin/View Logins page and Tutor Assignments button

---

javascript/src/main/pages/Admin/ViewLogins.js

Add ability to download a CSV of all logins to the application #238

hl - 6pm-4 add CSV button for downloading all logins

---

javascript/src/main/pages/Admin/Admin.js

Added a download button in the admins page that downloads a CSV of all the admins.

dw - 6pm-4 Add download button for a csv file of all Admins

---

javascript/src/main/pages/Admin/Admin.js

Add a download CSV button that downloads a CSV of all users on local machine

dw - Add a download csv button to download a csv of all users

---

javascript/src/main/pages/Tutor/Tutor.js

Added download csv button on tutors page that downloads all tutor data onto local machine

6pm-4-add download csv button on tutors page

---

javascript/src/main/pages/Admin/ViewLogins.js

Add a login count on the view logins page so admins can see the number of times people have logged in to the web application.

dw - 6pm-4-add a login count on view logins page

---

javascript/src/main/pages/TutorAssignment/TutorAssignments.js

Added a Download CSV button that downloads a CSV containing all ULA Tutor assignments onto local machine

rb - 6pm-4 - add a Download CSV button that downloads a CSV containing all ULA Tutor assignments

---

javascript/src/main/App.css
javascript/src/main/App.js

Modified footer so that it will stick on the bottom when there is not enough data, but no overlap with the data when there is enough data

6pm-1 cx -Modified footer so that it will stick on the bottom 

---

javascript/src/main/App.css
javascript/src/main/App.js

In this PR, we replace the custom ccs to use the existing bootstrap.

6pm-1 cx -replace custom ccs with existing bootstrap

---

javascript/src/main/App.js
javascript/src/main/components/OfficeHours/OfficeHourForm.js
javascript/src/main/components/OfficeHours/OfficeHourTable.js
javascript/src/main/pages/OfficeHours/EditOfficeHours.js
javascript/src/main/services/OfficeHours/OfficeHourService.js
javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
javascript/src/test/components/OfficeHours/OfficeHourTable.test.js
javascript/src/test/pages/OfficeHours/EditOfficeHours.test.js
javascript/src/test/services/OfficeHours/OfficeHourService.test.js
src/main/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHoursController.java
src/test/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHourControllerTests.java

In this PR, the team added the feature for editing existing office hours, as well as front-end and back-end testing

KW/CX 6pm-1 update office hour

---

javascript/src/main/pages/Admin/ViewLogins.js

added spacing between download CSV button and login table.
Before:
After:

6pm-1 Added spacing on the logins page

---

javascript/src/main/components/OfficeHours/OfficeHourTable.js

Added tutor name, course name, and quarter to office hour table. Previously only showed tutor assignment id, which made it difficult to tell who was hosting the office hour and which course it was for.

KW/CX 6pm-1 added tutor name, course name, and quarter to office hour table

---

javascript/src/main/components/OfficeHours/OfficeHourCSVButton.js
javascript/src/main/pages/OfficeHours/OfficeHours.js
javascript/src/main/services/OfficeHours/UploadCSV.js
javascript/src/test/components/OfficeHours/OfficeHourCSVButton.test.js
javascript/src/test/pages/OfficeHours/OfficeHours.test.js
javascript/src/test/services/OfficeHours/OfficeHourService.test.js
src/main/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHoursController.java
src/main/java/edu/ucsb/ucsbcslas/entities/OnlineOfficeHours.java
src/main/java/edu/ucsb/ucsbcslas/entities/Tutor.java
src/main/java/edu/ucsb/ucsbcslas/entities/TutorAssignment.java
src/main/java/edu/ucsb/ucsbcslas/models/Course.java
src/main/java/edu/ucsb/ucsbcslas/repositories/TutorAssignmentRepository.java
src/test/java/edu/ucsb/ucsbcslas/controllers/OnlineOfficeHourControllerTests.java
src/test/java/edu/ucsb/ucsbcslas/entities/OnlineOfficeHoursTests.java
src/test/java/edu/ucsb/ucsbcslas/entities/TutorAssignmentTests.java
src/test/java/edu/ucsb/ucsbcslas/entities/TutorTests.java
src/test/java/edu/ucsb/ucsbcslas/models/CourseTests.java

In this PR, I enable the users to upload CSV function for Office Hours, so that users can import large amount of data at one click instead of adding them one by one.

6pm-4-add upload CSV to Office Hours

---

javascript/package.json
javascript/src/fixtures/tutorAssignmentFixtures.js
javascript/src/main/components/OfficeHours/OfficeHourForm.js
javascript/src/main/components/TutorAssignment/TutorAssignmentDisplay.js
javascript/src/stories/components/TutorAssignment/TutorAssignmentDisplay.stories.js
javascript/src/test/components/OfficeHours/OfficeHourForm.test.js
javascript/src/test/pages/OfficeHours/EditOfficeHours.test.js
javascript/src/test/pages/OfficeHours/NewOfficeHours.test.js

In this PR, we update the office hour form so that the user will not be able to edit the tutor when they update the office hour.

6pm-1 CX/KW -user couldn't edit tutor name when they update office hour

---

javascript/src/fixtures/officeHoursFixtures.js
javascript/src/main/components/OfficeHours/OfficeHoursSelector.js
javascript/src/stories/components/OfficeHours/OfficeHoursSelector.stories.js
javascript/src/test/components/OfficeHours/OfficeHoursSelector.test.js

In this front end only issue, we create a component called OfficeHoursSelector.
This component accepts an array of OfficeHours in the json format provided by the back end, and it displays that list as a dropdown menu.
It provides a onChange function that will be passed the index of whatever office hours entry was selected.
This can be used on the TutorNotes creation form to select a specific office hours slot

6pm 3 office hours selector

---

javascript/src/main/pages/TutorAssignment/TutorAssignments.js

There was an error with deleting tutor assignments because the error function is not defined.

pc/wv - hot fix for deleting tutor assignment

---

src/main/java/edu/ucsb/ucsbcslas/controllers/TutorNotesController.java

Changed list to set in the @getMapping in TutorNotesContoller.java. This makes it so that when a tutor admin attempts to create and entry it will no longer create two entries. Allows for a TutorNote to be made by a tutor and admin without any bugss.
This should prevent duplicate entries when using the api/member/tutorNotes

6pm-3 Bug fix, backend was doubling entries to database; removed that issue
